# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\tgstreamer\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n\x05\x46rame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x06\n\x04Void2=\n\x0b\x46rameSender\x12.\n\tSendFrame\x12\x10.gstreamer.Frame\x1a\x0f.gstreamer.Voidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAME']._serialized_start=59
  _globals['_FRAME']._serialized_end=127
  _globals['_VOID']._serialized_start=129
  _globals['_VOID']._serialized_end=135
  _globals['_FRAMESENDER']._serialized_start=137
  _globals['_FRAMESENDER']._serialized_end=198
# @@protoc_insertion_point(module_scope)
