# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gps_1403_pb2 as gps__1403__pb2


class DataGPSServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendGPSData = channel.unary_unary(
                '/gps_1403.DataGPSService/SendGPSData',
                request_serializer=gps__1403__pb2.DataGPS.SerializeToString,
                response_deserializer=gps__1403__pb2.DataGPS.FromString,
                )


class DataGPSServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendGPSData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataGPSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendGPSData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGPSData,
                    request_deserializer=gps__1403__pb2.DataGPS.FromString,
                    response_serializer=gps__1403__pb2.DataGPS.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gps_1403.DataGPSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataGPSService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendGPSData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gps_1403.DataGPSService/SendGPSData',
            gps__1403__pb2.DataGPS.SerializeToString,
            gps__1403__pb2.DataGPS.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
